name: Automatización de scraping web

on:
  schedule:
    # Ejecutar los lunes, miércoles y viernes
    - cron: '0 0 * * 1,3,5'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    # Instalar dependencias
    - name: Instalar dependencias
      run: pip install -r requirements.txt

    # Instalar Firefox
    - name: Instalar Firefox
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox-esr

    # Ejecutar scripts de scraping
    - name: Ejecutar scripts de scraping
      run: |
        for file in *.py; do
          python "$file"
        done

    # Subir la base de datos
    - name: Subir base de datos
      uses: actions/upload-artifact@v2
      with:
        name: precios_competencia.db
        path: precios_competencia.db

    # Generar y subir Excel
    - name: Generar y subir Excel
      run: |
        python 6listas_en_excel.py
        
    # Subir archivo Excel
    - name: Subir archivo Excel
      uses: actions/upload-artifact@v2
      with:
        name: precios_competencia.xlsx
        path: precios_competencia.xlsx


