name: Automatizaci贸n de scraping web

on:
  schedule:
    # Ejecutar todos los lunes
    - cron: '0 0 * * 1'
  
  # Permitir ejecuci贸n manual
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}  # EMAIL_ADDRESS
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  # EMAIL_PASSWORD
      DESTINATARIO_EMAIL: ${{ secrets.DESTINATARIO_EMAIL }}  # DESTINATARIO_EMAIL

    steps:

    - uses: actions/checkout@v2

    # Instalar dependencias
    - name: Instalar dependencias
      run: pip install -r requirements.txt

    # Instalar Firefox
    - name: Instalar Firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: 'latest'

    # Descargar geckodriver
    - name: Descargar geckodriver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.34.0-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/

    # Verificar la instalaci贸n de geckodriver
    - name: Verificar la instalaci贸n de geckodriver
      run: |
        geckodriver --version

    # Configurar Xvfb
    - name: Configurar Xvfb
      run: |
        sudo apt-get install -y xvfb
        Xvfb :99 & 
        echo "DISPLAY=:99.0" >> $GITHUB_ENV

    # Ejecutar scripts de scraping
    - name: Ejecutar scripts de scraping
      run: |
        for file in *.py; do
          python "$file"
        done

    # Subir la base de datos
    - name: Subir base de datos
      uses: actions/upload-artifact@v2
      with:
        name: precios_competencia.db
        path: precios_competencia.db

    # Generar y subir Excel
    - name: Generar y subir Excel
      run: |
        python 6listas_en_excel.py
        
    # Subir archivo Excel
    - name: Subir archivo Excel
      uses: actions/upload-artifact@v2
      with:
        name: precios_competencia.xlsx
        path: precios_competencia.xlsx



